spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD:}

redis:
  stream:
    name: ${REDIS_STREAM_NAME:stream:dou.jobs}
    key: ${REDIS_STREAM_KEY:job}
  set:
    name: ${REDIS_SET_NAME:processed:jobs}